---
apiVersion: v1
kind: Secret
metadata:
  name: leaderboard-git
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: $GITHUB_USERNAME
  password: $GITHUB_PAT
---
apiVersion: v1
kind: Secret
metadata:
  name: leaderboard-quay
  annotations:
    tekton.dev/docker-0: https://quay.io/v2
type: kubernetes.io/basic-auth
stringData:
  username: $QUAY_USERNAME
  password: $QUAY_PASSWORD
