---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  #storageClassName: iops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgwal-pvc
spec:
  #storageClassName: iops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ${PG_SERVICE_NAME}
spec:
  selector:
    app: postgresql
  ports:
    - name: pgsql
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: quay.io/redhatdemo/openshift-pgsql12-primary:centos7
          imagePullPolicy: Always
          resources:
            limits:
              memory: "8Gi"
              cpu: "6"
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: PG_USER_PASSWORD
              value: password!
            - name: PG_USER_NAME
              value: demo
            - name: PG_DATABASE
              value: gamedb
            - name: PG_NETWORK_MASK
              value: all
            - name: PG_MAX_CONNECTIONS
              value: "800"
            # 25% of the memory in mb
            - name: PG_SHARED_BUFFERS
              value: "2048"
            - name: PG_WORK_MEM
              value: "1536"
            # 75% of the memory in GB
            - name: PG_EFFECTIVE_CACHE_SIZE
              value: "6"
            - name: PG_EFFECTIVE_IO
              value: "128"
            # 20% of the Disk size
            - name: PG_MAX_WAL_SIZE
              value: "4"
          volumeMounts:
            - mountPath: /pgdata
              name: pgdata
            - mountPath: /pgwal
              name: pgwal
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc
        - name: pgwal
          persistentVolumeClaim:
            claimName: pgwal-pvc
