---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgwal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: Secret
apiVersion: v1
metadata:
  name: openshift-pgsql12-primary-secret
stringData:
  database-db: "gamedb"
  database-username: "demo"
  database-username-password: "password!"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: pgsql
      port: 5432
      targetPort: 5432
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: quay.io/rhdevelopers/openshift-pgsql12-primary:centos7-monitoring
          imagePullPolicy: Always
          resources:
            limits:
              memory: "16Gi"
              cpu: "6"
            requests:
              memory: "8Gi"
              cpu: "4"
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: PG_USER_PASSWORD
              value: password!
            - name: PG_USER_NAME
              value: demo
            - name: PG_DATABASE
              value: gamedb
            - name: PG_NETWORK_MASK
              value: all
            - name: PG_MAX_CONNECTIONS
              value: "500"
            # 25% of the memory in mb
            - name: PG_SHARED_BUFFERS
              value: "2048"
            - name: PG_WORK_MEM
              value: "1536"
            # 75% of the memory in GB
            - name: PG_EFFECTIVE_CACHE_SIZE
              value: "6"
            - name: PG_EFFECTIVE_IO
              value: "128"
            # 20% of the Disk size
            - name: PG_MAX_WAL_SIZE
              value: "4"
          volumeMounts:
            - mountPath: /pgdata
              name: pgdata
            - mountPath: /pgwal
              name: pgwal
        - name: client
          image: quay.io/rhdevelopers/openshift-pgsql12-primary:centos7-clients
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PG_USER_PASSWORD
              value: password!
            - name: PG_USER_NAME
              value: demo
            - name: PG_DATABASE
              value: gamedb
            - name: PG_HOST
              value: localhost
          volumeMounts:
            - mountPath: /opt/sql
              name: appsql
            - mountPath: /pgdata
              name: pgdata
              readOnly: true
      volumes:
        - name: appsql
          configMap:
            name: appsql
            items:
              - key: schema.sql
                path: schemas/schema.sql
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc
        - name: pgwal
          persistentVolumeClaim:
            claimName: pgwal-pvc
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: loganalyzer
spec:
  to:
    kind: Service
    name: postgresql
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
